"""database update55

Revision ID: 02326ecdb334
Revises: 2991a2d5d2be
Create Date: 2018-01-26 14:11:59.097352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02326ecdb334'
down_revision = '2991a2d5d2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('seat_num', sa.Integer(), nullable=True))
    op.add_column('mstations', sa.Column('bus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mstations', 'mbuses', ['bus_id'], ['id'])
    op.add_column('musers', sa.Column('mailaddr', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'mailaddr')
    op.drop_constraint(None, 'mstations', type_='foreignkey')
    op.drop_column('mstations', 'bus_id')
    op.drop_column('mbuses', 'seat_num')
    # ### end Alembic commands ###
