"""update v0.72_4

Revision ID: 0cf029697c0d
Revises: 6cc2f1ca7e50
Create Date: 2018-03-26 13:58:45.059776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf029697c0d'
down_revision = '6cc2f1ca7e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'about_me')
    # ### end Alembic commands ###
