"""remotedbaccess

Revision ID: 17ee6a818239
Revises: 43eb0572dde4
Create Date: 2018-04-01 17:20:21.346981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ee6a818239'
down_revision = '43eb0572dde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CarID', sa.String(length=20), nullable=True),
    sa.Column('DateTimes', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
