"""database update3

Revision ID: 21880da6c6df
Revises: f52da2515b24
Create Date: 2018-01-26 10:35:21.367822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21880da6c6df'
down_revision = 'f52da2515b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mstations_name', table_name='mstations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mstations_name', 'mstations', ['name'], unique=False)
    # ### end Alembic commands ###
