"""addseat_num

Revision ID: 260aa48d88cf
Revises: 367eca13f30b
Create Date: 2018-03-28 12:30:38.685816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260aa48d88cf'
down_revision = '367eca13f30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('seat_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'seat_num')
    # ### end Alembic commands ###
