"""database update4

Revision ID: 2991a2d5d2be
Revises: 4d4e2e134586
Create Date: 2018-01-26 14:10:43.603352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2991a2d5d2be'
down_revision = '4d4e2e134586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'seat_num')
    op.drop_constraint('mstations_ibfk_1', 'mstations', type_='foreignkey')
    op.drop_column('mstations', 'bus_id')
    op.drop_column('musers', 'mailaddr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('mailaddr', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('mstations', sa.Column('bus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mstations_ibfk_1', 'mstations', 'mbuses', ['bus_id'], ['id'])
    op.add_column('mbuses', sa.Column('seat_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
