"""update v0.72_6

Revision ID: 3ab434d1afe1
Revises: d9425f550cb8
Create Date: 2018-03-26 14:04:19.533776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab434d1afe1'
down_revision = 'd9425f550cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mposts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mposts', 'musers', ['author_id'], ['id'])
    op.add_column('musers', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'musers', 'mroles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musers', type_='foreignkey')
    op.drop_column('musers', 'role_id')
    op.drop_constraint(None, 'mposts', type_='foreignkey')
    op.drop_column('mposts', 'author_id')
    # ### end Alembic commands ###
