"""update_rectime2

Revision ID: 43eb0572dde4
Revises: 8489b05375a3
Create Date: 2018-03-28 14:23:30.529079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eb0572dde4'
down_revision = '8489b05375a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('lefttime', sa.Float(precision='11,7'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'lefttime')
    # ### end Alembic commands ###
