"""diagram3

Revision ID: 4714bcd8b8e0
Revises: a934282ee22e
Create Date: 2018-04-03 16:31:15.955023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4714bcd8b8e0'
down_revision = 'a934282ee22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagrams', sa.Column('mdate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'mdate')
    # ### end Alembic commands ###
