"""addapplystation

Revision ID: 477d243998ef
Revises: f8dd4e2835d8
Create Date: 2018-04-07 07:36:37.641683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477d243998ef'
down_revision = 'f8dd4e2835d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('applydesc', sa.String(length=64), nullable=True))
    op.add_column('musers', sa.Column('applyflag', sa.Boolean(), nullable=True))
    op.add_column('musers', sa.Column('lat', sa.Float(precision='11,8'), nullable=True))
    op.add_column('musers', sa.Column('lon', sa.Float(precision='11,8'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'lon')
    op.drop_column('musers', 'lat')
    op.drop_column('musers', 'applyflag')
    op.drop_column('musers', 'applydesc')
    # ### end Alembic commands ###
