"""musercampusadded

Revision ID: 4d181fbc65fa
Revises: 620a46f45195
Create Date: 2018-03-15 10:18:45.851864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d181fbc65fa'
down_revision = '620a46f45195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('campus', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'campus')
    # ### end Alembic commands ###
