"""update database5

Revision ID: 4d4e2e134586
Revises: 0cdbbcd3e00e
Create Date: 2018-01-26 11:18:54.903149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4e2e134586'
down_revision = '0cdbbcd3e00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('recordtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'recordtime')
    # ### end Alembic commands ###
