"""addcampus

Revision ID: 4e298ad5ce0b
Revises: 70d5bda17a8d
Create Date: 2018-02-02 14:08:31.476066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e298ad5ce0b'
down_revision = '70d5bda17a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('campus', sa.String(length=64), nullable=True))
    op.add_column('mstations', sa.Column('campus', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mstations', 'campus')
    op.drop_column('mbuses', 'campus')
    # ### end Alembic commands ###
