"""addgps3

Revision ID: 620a46f45195
Revises: a198a8aaed18
Create Date: 2018-03-09 11:54:05.168474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620a46f45195'
down_revision = 'a198a8aaed18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('abntime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'abntime')
    # ### end Alembic commands ###
