"""adddir

Revision ID: 6c5525233db9
Revises: 477d243998ef
Create Date: 2018-04-10 13:57:20.324309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5525233db9'
down_revision = '477d243998ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('currdir', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'currdir')
    # ### end Alembic commands ###
