"""update v0.72_2

Revision ID: 6d88e8e532e3
Revises: a233a77c5723
Create Date: 2018-03-26 13:53:23.068776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d88e8e532e3'
down_revision = 'a233a77c5723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'about_me')
    # ### end Alembic commands ###
