"""mbus table updated

Revision ID: 70d5bda17a8d
Revises: ace71086f7c4
Create Date: 2018-01-31 09:04:23.730335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d5bda17a8d'
down_revision = 'ace71086f7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('buslicense', sa.String(length=64), nullable=True))
    op.add_column('mbuses', sa.Column('color', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'color')
    op.drop_column('mbuses', 'buslicense')
    # ### end Alembic commands ###
