"""update database99

Revision ID: 900d01694f5d
Revises: 896d3ce47b90
Create Date: 2018-01-26 14:36:09.143352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900d01694f5d'
down_revision = '896d3ce47b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mstations', sa.Column('bus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mstations', 'mbuses', ['bus_id'], ['id'])
    op.add_column('musers', sa.Column('mailaddr', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'mailaddr')
    op.drop_constraint(None, 'mstations', type_='foreignkey')
    op.drop_column('mstations', 'bus_id')
    # ### end Alembic commands ###
