"""update v0.72

Revision ID: a233a77c5723
Revises: 4d181fbc65fa
Create Date: 2018-03-26 13:49:24.131776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a233a77c5723'
down_revision = '4d181fbc65fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('musers', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('about_me', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
