"""diagram2

Revision ID: a934282ee22e
Revises: c1a7c7615ef1
Create Date: 2018-04-03 16:30:14.717425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a934282ee22e'
down_revision = 'c1a7c7615ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'mdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagrams', sa.Column('mdate', mysql.TIME(), nullable=True))
    # ### end Alembic commands ###
