"""update database10

Revision ID: ace71086f7c4
Revises: 900d01694f5d
Create Date: 2018-01-26 15:33:36.571352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace71086f7c4'
down_revision = '900d01694f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mroles_default'), 'mroles', ['default'], unique=False)
    op.create_table('mposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['musers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mposts_timestamp'), 'mposts', ['timestamp'], unique=False)
    op.add_column('musers', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('musers', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.add_column('musers', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('musers', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('musers', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('musers', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('musers', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('musers', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('musers', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('musers', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_musers_username'), 'musers', ['username'], unique=True)
    op.create_foreign_key(None, 'musers', 'mroles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musers', type_='foreignkey')
    op.drop_index(op.f('ix_musers_username'), table_name='musers')
    op.drop_column('musers', 'username')
    op.drop_column('musers', 'role_id')
    op.drop_column('musers', 'password_hash')
    op.drop_column('musers', 'name')
    op.drop_column('musers', 'member_since')
    op.drop_column('musers', 'location')
    op.drop_column('musers', 'last_seen')
    op.drop_column('musers', 'confirmed')
    op.drop_column('musers', 'avatar_hash')
    op.drop_column('musers', 'about_me')
    op.drop_index(op.f('ix_mposts_timestamp'), table_name='mposts')
    op.drop_table('mposts')
    op.drop_index(op.f('ix_mroles_default'), table_name='mroles')
    op.drop_table('mroles')
    # ### end Alembic commands ###
