"""abnleftDist

Revision ID: c1a7c7615ef1
Revises: 9efdae4bb717
Create Date: 2018-04-02 10:56:17.005904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a7c7615ef1'
down_revision = '9efdae4bb717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mbuses', sa.Column('abnleftDist', sa.Float(precision='11,7'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mbuses', 'abnleftDist')
    # ### end Alembic commands ###
