"""update v0.72_5

Revision ID: d9425f550cb8
Revises: 0cf029697c0d
Create Date: 2018-03-26 14:02:00.032776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9425f550cb8'
down_revision = '0cf029697c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mposts_ibfk_1', 'mposts', type_='foreignkey')
    op.drop_column('mposts', 'author_id')
    op.drop_constraint('musers_ibfk_1', 'musers', type_='foreignkey')
    op.drop_column('musers', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musers', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('musers_ibfk_1', 'musers', 'mroles', ['role_id'], ['id'])
    op.add_column('mposts', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mposts_ibfk_1', 'mposts', 'musers', ['author_id'], ['id'])
    # ### end Alembic commands ###
