"""update database

Revision ID: dd50eea8d165
Revises: 27eebbd32d76
Create Date: 2018-01-25 16:27:45.788588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd50eea8d165'
down_revision = '27eebbd32d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cz_name', sa.String(length=64), nullable=True),
    sa.Column('cz_phone', sa.String(length=30), nullable=True),
    sa.Column('sj_name', sa.String(length=64), nullable=True),
    sa.Column('sj_phone', sa.String(length=64), nullable=True),
    sa.Column('seat_num', sa.Integer(), nullable=True),
    sa.Column('equip_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(precision='11,8'), nullable=True),
    sa.Column('lon', sa.Float(precision='11,8'), nullable=True),
    sa.Column('recordtime', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mbuses_name'), 'mbuses', ['name'], unique=False)
    op.create_table('musers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailaddr', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('dirtocompany', sa.Boolean(), nullable=True),
    sa.Column('lat', sa.Float(precision='11,8'), nullable=True),
    sa.Column('lon', sa.Float(precision='11,8'), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['mbuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mstations_name'), 'mstations', ['name'], unique=False)
    op.create_table('diagrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mdate', sa.Time(), nullable=True),
    sa.Column('arrive_time', sa.Time(), nullable=True),
    sa.Column('current_num', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['mstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['mstations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['mbuses.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    op.drop_table('diagrams')
    op.drop_index(op.f('ix_mstations_name'), table_name='mstations')
    op.drop_table('mstations')
    op.drop_table('musers')
    op.drop_index(op.f('ix_mbuses_name'), table_name='mbuses')
    op.drop_table('mbuses')
    # ### end Alembic commands ###
