"""update database66

Revision ID: f0dd92537763
Revises: 02326ecdb334
Create Date: 2018-01-26 14:33:34.535352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0dd92537763'
down_revision = '02326ecdb334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mstations_ibfk_1', 'mstations', type_='foreignkey')
    op.drop_column('mstations', 'bus_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mstations', sa.Column('bus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mstations_ibfk_1', 'mstations', 'mbuses', ['bus_id'], ['id'])
    # ### end Alembic commands ###
