"""addbusdiagram

Revision ID: f8dd4e2835d8
Revises: 4714bcd8b8e0
Create Date: 2018-04-06 09:38:30.686767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dd4e2835d8'
down_revision = '4714bcd8b8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busdiagrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mdate', sa.Date(), nullable=True),
    sa.Column('arrive_time', sa.Time(), nullable=True),
    sa.Column('tocomp_num', sa.Integer(), nullable=True),
    sa.Column('tohome_num', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('busdiagrams')
    # ### end Alembic commands ###
